use anyhow::Result;
use uuid::Uuid;

use crate::storage::sqlite::SqliteStorage;

/// Generate an incident report in the specified format.
pub async fn generate_report(pg: &SqliteStorage, incident_id: Uuid, format: &str) -> Result<String> {
    let incident = pg
        .get_incident(incident_id)
        .await?
        .ok_or_else(|| anyhow::anyhow!("Incident {} not found", incident_id))?;

    let findings = pg.get_findings(incident_id).await?;

    match format {
        "markdown" | "md" => generate_markdown(&incident, &findings),
        "text" | "txt" => generate_text(&incident, &findings),
        _ => generate_markdown(&incident, &findings),
    }
}

fn generate_markdown(
    incident: &crate::models::StoredIncident,
    findings: &[crate::models::StoredFinding],
) -> Result<String> {
    let mut out = String::new();

    out.push_str("# Incident Report\n\n");
    out.push_str(&format!(
        "**Date:** {}\n\n",
        incident.created_at.format("%Y-%m-%d %H:%M:%S UTC")
    ));
    out.push_str(&format!("**ID:** `{}`\n\n", incident.id));

    if let Some(ref title) = incident.title {
        out.push_str(&format!("**Title:** {}\n\n", title));
    }

    out.push_str("## Symptom\n\n");
    out.push_str(&format!("{}\n\n", incident.symptom));

    out.push_str("## Affected Node\n\n");
    out.push_str(&format!("`{}`\n\n", incident.affected_node));

    out.push_str("## Probable Cause Candidates\n\n");

    if findings.is_empty() {
        out.push_str("No candidates identified.\n\n");
    } else {
        out.push_str("| # | Candidate | Score | Reason |\n");
        out.push_str("|---|-----------|-------|--------|\n");

        for (i, f) in findings.iter().enumerate() {
            out.push_str(&format!(
                "| {} | `{}` | {:.2} | {} |\n",
                i + 1,
                f.candidate_node,
                f.score,
                f.reason.as_deref().unwrap_or("-")
            ));
        }
        out.push('\n');
    }

    out.push_str("## Impact Assessment\n\n");
    out.push_str("Components potentially affected by the root cause:\n\n");
    for f in findings {
        out.push_str(&format!("- `{}`\n", f.candidate_node));
    }
    out.push('\n');

    out.push_str("## Observations\n\n");
    out.push_str("> **Note:** This analysis is based on heuristic scoring of known dependency\n");
    out.push_str("> relationships. The scores indicate relative probability, not certainty.\n");
    out.push_str("> Always validate findings with actual system logs and monitoring data.\n\n");

    out.push_str("---\n");
    out.push_str("*Generated by rootmap — Linux Infrastructure Dependency Mapper*\n");

    Ok(out)
}

fn generate_text(
    incident: &crate::models::StoredIncident,
    findings: &[crate::models::StoredFinding],
) -> Result<String> {
    let mut out = String::new();

    out.push_str("========================================\n");
    out.push_str("         INCIDENT REPORT\n");
    out.push_str("========================================\n\n");

    out.push_str(&format!(
        "Date:     {}\n",
        incident.created_at.format("%Y-%m-%d %H:%M:%S UTC")
    ));
    out.push_str(&format!("ID:       {}\n", incident.id));

    if let Some(ref title) = incident.title {
        out.push_str(&format!("Title:    {}\n", title));
    }

    out.push_str(&format!("Symptom:  {}\n", incident.symptom));
    out.push_str(&format!("Affected: {}\n\n", incident.affected_node));

    out.push_str("PROBABLE CAUSE CANDIDATES\n");
    out.push_str("─────────────────────────\n\n");

    if findings.is_empty() {
        out.push_str("No candidates identified.\n\n");
    } else {
        for (i, f) in findings.iter().enumerate() {
            out.push_str(&format!(
                "  {}. {} (score={:.2})\n",
                i + 1,
                f.candidate_node,
                f.score
            ));
            if let Some(ref reason) = f.reason {
                out.push_str(&format!("     Reason: {}\n", reason));
            }
            out.push('\n');
        }
    }

    out.push_str("NOTE: Results are heuristic hypotheses, not definitive conclusions.\n");
    out.push_str("\n-- Generated by rootmap\n");

    Ok(out)
}
